project_id = "sovlfqncotxcjqseeawp"

[functions.parse-menu-pdf]
verify_jwt = true

[functions.send-order-notification]
verify_jwt = false

[functions.calculate-delivery]
verify_jwt = false

[functions.create-lexoffice-invoice]
verify_jwt = false

[functions.create-catering-payment]
verify_jwt = false

[functions.get-lexoffice-document]
verify_jwt = true
